### ISSUE TITLE
TTL support

### ISSUE THREAD

**Issue by nihaals** [Emka877/pushover-rs#1]
Pushover supports a [TTL field](https://pushover.net/api#ttl) and it's not currently possible to provide a value for it.

**Comment by Emka877** [comment]
Hello, thank you for your feedback.
I'll have a look into it and will push support for it.

**Comment by Emka877** [comment]
Hello again @nihaals 
I've tested and pushed an update to allow usage of this option, please tell me if it works for you as well

**Comment by nihaals** [comment]
Looks great, thanks! I also made #2 regarding the example comment.
